parser: babel-eslint

env:
  browser: true
  node: true
  es6: true

plugins:
- es-beautifier
- angular

extends: 
- eslint:recommended
- google
- plugin:angular/johnpapa

globals:
  angular: true

rules:
  indent:
  - error
  - 2
  - MemberExpression: off
  max-len:
  - error
  - code: 120
  semi:
  - error
  - always
  valid-jsdoc:
  - error
  - requireReturnDescription: false
  no-invalid-this:
  - off
  require-jsdoc:
  - off

  # angular.js
  angular/file-name:
  - error
  - typeSeparator: dot
  angular/controller-name:
  - off