env:
  node: true
  es6: true

root: true

plugins:
- es-beautifier

extends: 
- eslint:recommended
- google

rules:
  indent:
  - error
  - 2
  - MemberExpression: off
  max-len:
  - error
  - code: 120
  semi:
  - error
  - always
  valid-jsdoc:
  - error
  - requireReturnDescription: false
  require-jsdoc:
  - off
  no-unused-vars:
  - error
  no-console:
  - off